### ISSUE TITLE
missed canonical action?

### ISSUE THREAD

**Issue by joyously** [omnisite/WP-Plugin-Remove-Wordpress-Overhead#4]
https://github.com/omnisite/WP-Plugin-Remove-Wordpress-Overhead/blob/15e621f844cdc370ac00e40359f390125e975a1c/includes/class-remove-wordpress-overhead.php#L314

This code removes the action from `embed_head` but what about the default action on `wp_head`?
https://core.trac.wordpress.org/browser/trunk/src/wp-includes/default-filters.php#L339
`add_action( 'wp_head', 'rel_canonical' );`

**Comment by omnisite** [comment]
Thanks! I added it to the code and also in master. Will update the plugin in the WP repo soon (see mention in readme file)
